name: binbiralem
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  vexana: ^3.0.1
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.1
  firebase_core: ^1.24.0
  firebase_analytics: ^9.3.7
  logger: ^1.1.0
  # cached_network_image: ^3.2.2
  animations: ^2.0.5
  flutter_svg: ^1.1.5
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  pedantic: ^1.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
